services:
  - type: web
    name: backend
    runtime: python
    env: python
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r app/requirements.txt
    startCommand: uvicorn app.server:app --host=0.0.0.0 --port=10000
    pythonVersion: 3.11.9
